project:
  type: default

# jupyter:
#   kernelspec:
#     name: "python"
#     display_name: "Python 3"
#     language: "python"
#   python: "/Users/kristjanrox/work/hi/vel407g_honvel/.venv/bin/python"